#!/usr/bin/env zsh
function fzf-change-directory {
   __fzf::widget::init 'cd --' || return 1

   eval "${FZF_CHANGE_DIR_FIND_COMMAND:-"fd . --type d --type l 2>/dev/null"}" |\
      sed 's|\./||g' | \
      __fzf::widget::select ${FZF_WIDGET_OPTS[change-dir]} +m | \
      __fzf::widget::insert -q
 
   __fzf::widget::exec
}
