#!/bin/zsh

__fzf::widget::init || return 1

eval "${FZF_INSERT_DIR_FIND_COMMAND:-"fd --strip-cwd-prefix --follow --type d --type l --exclude '.*' --exclude 'dev' --exclude 'proc' --exclude 'sys' 2> /dev/null"}" | \
  __fzf::widget::select ${FZF_WIDGET_OPTS[insert-directory]} +m | \
  __fzf::widget::insert -q
